name: Packer Build

on:
  push:
    tags:
      - v*
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.PACKER_SA_KEY }}
jobs:
  packer-build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Packer project
        uses: actions/checkout@v2

      # init plugins
      - name: Init plugins
        uses: hashicorp/packer-github-actions@master
        with:
          command: init

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: runner-machine-image.pkr.hcl
      
      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: '-on-error=abort -var=ghrunner_version=${GITHUB_REF_NAME} -var-file=runtime-variables.pkrvars.hcl'
          target: runner-machine-image.pkr.hcl