name: Packer Build

on:
  push:
    tags:
      - v*
jobs:
  packer-build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Packer project
        uses: actions/checkout@v2

      - name: Export Application Credentials
        run: |
          echo ${PACKER_SA_KEY} > $GOOGLE_APPLICATION_CREDENTIALS
        env:
          PACKER_SA_KEY: ${{ secrets.PACKER_SA_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/packer_sa_key.json

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-var=ghrunner_version=$GITHUB_REF_NAME -var-file=runtime-variables.pkrvars.hcl"
          target: .
        env:
          PACKER_LOG: 1