name: Packer Build

on:
  push:
    tags:
      - v*
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.PACKER_SA_KEY }}
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Packer project
        uses: actions/checkout@v2
      - name: Dummy step
        run: |
          echo Done