name: Packer Build

on:
  push:
    branches:
      - main
    # tags:
    #   - v*
env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.PACKER_SA_KEY }}
jobs:
  packer-build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Packer project
        uses: actions/checkout@v2
      
      # packer version
      - name: Packer Installation
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
          packer
      
      # # packer init
      # - name: Packer Init
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: init

      # # validate templates
      # - name: Validate Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: validate
      #     target: runner-machine-image.pkr.hcl
      
      # # build artifact
      # - name: Build Artifact
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: build
      #     # arguments: '-on-error=abort -var=ghrunner_version=${GITHUB_REF_NAME} -var-file=runtime-variables.pkrvars.hcl'
      #     arguments: '-on-error=abort -var=ghrunner_version=v2.283.3 -var-file=runtime-variables.pkrvars.hcl'
      #     target: runner-machine-image.pkr.hcl