name: Packer Build

on:
  push:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-20.04
    environment: gcp
    steps:
      - name: Checkout Packer project
        uses: actions/checkout@v3

      - name: Initialize Packer Plugin Binaries
        run: packer init .

      - name: Build Image
        env:
          PKR_VAR_project: ${{ secrets.GOOGLE_PROJECT }}
          GOOGLE_APPLICATION_CREDENTIALS: gcp.json
        run: |
          cat > $GOOGLE_APPLICATION_CREDENTIALS << EOF
          ${{ secrets.GOOGLE_CREDENTIALS }}
          EOF
          trap "rm -f $GOOGLE_APPLICATION_CREDENTIALS" EXIT
          packer build -force .