name: Packer Build

on:
  push:
    tags:
      - v*
jobs:
  packer-build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Packer project
        uses: actions/checkout@v2

      - name: Packer Init
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
          packer init .
          packer fmt .
          packer validate -var=ghrunner_version=v2.283.3 -var-file=runtime-variables.pkrvars.hcl .

      - name: Build Packer Artifact
        env:
          PACKER_SA_KEY: ${{ secrets.PACKER_SA_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: /home/runner/packer_sa_key.json
        run: |
          echo ${PACKER_SA_KEY} > /home/runner/packer_sa_key.json
          packer build -var='ghrunner_version=$GITHUB_REF_NAME' -var-file='runtime-variables.pkrvars.hcl' .