name: lint

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Initialize Packer Plugin Binaries
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: .

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -var=ghrunner_version=v1.0.0 -var-file=runtime-variables.pkrvars.hcl
          target: .
