name: lint

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main
    pull_requests:
jobs:
  validate:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        env:
          DUMMY_VERSION_FOR_CODE_VALIDATION: v1.0.0
        with:
          command: validate
          arguments: "-var=ghrunner_version=${DUMMY_VERSION_FOR_CODE_VALIDATION} -var-file=runtime-variables.pkrvars.hcl"
          target: .