name: Check For Latest Versions

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  check-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Packer Project
        uses: actions/checkout@v3
      - name: Print Current Runner Version
        run: cat versions.json| jq '.runner'
      - name: Print Latest Runner Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh api /repos/actions/runner/releases/latest | jq -r .tag_name
