name: Check For Latest Versions

# on:
#   schedule:
#     - cron:  '*/5 * * * *'

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Packer Project
        uses: actions/checkout@v3
      - name: Compare versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_version=$(cat versions.json| jq -r '.runner')
          latest_version=$(gh api /repos/actions/runner/releases/latest | jq -r .tag_name)
          matching=false
          if [ "$current_version" = "$latest_version" ]; then
              matching=true;
          fi
          echo $matching
