name: Check For Latest Versions

# on:
#   schedule:
#     - cron:  '*/5 * * * *'

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Packer Project
        uses: actions/checkout@v3
      - name: Compare versions
        id: compare-versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_version=$(cat versions.json | jq -r '.runner')
          latest_version=$(gh api /repos/actions/runner/releases/latest | jq -r .tag_name)
          if [ "$current_version" = "$latest_version" ]; then
              matching=true;
          else
              echo '${{ toJSON(github) }}'
              git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
              git checkout -b bump-versions-${{ github.job }}
              cat versions.json | jq --arg v "$latest_version" '.runner = ($v)' > tmp.json
              cat tmp.json > versions.json
              rm tmp.json
              git add .
              git commit -m "[bot] Bump versions"
              git push origin bump-versions-${{ github.job }}
              matching=false
          fi
          echo "::set-output name=matching::$matching"
      - name: Create PR
        if: ${{ steps.compare-versions.outputs.matching == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --title "[bot] Bump versions" --body "Versions bumped" -B bump-versions-${{ github.job }} -H main

